[package]
name = "client"
version.workspace = true
edition.workspace = true

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
protocol     = { path = "../protocol" }
tokio         = { version = "1", features = ["full"] }

rustls        = { version = "0.23", features = ["ring"] }
tokio-rustls  = "0.26"
webpki-roots  = "0.26"
tokio-tungstenite = { version = "0.26" }   # 不带 rustls feature，手动做 TLS
futures-util  = "0.3"
anyhow        = "1"
tracing       = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
base64        = "0.22"
rand          = "0.9"
url           = "2"
clap          = { version = "4", features = ["derive"] }
serde         = { version = "1", features = ["derive"] }
serde_yaml    = "0.9"
bytes         = "1"
libc          = "0.2"
socket2       = { version = "0.5", features = ["all"] }
axum          = "0.8"
serde_json    = "1"
console-subscriber = { version = "0.5", optional = true }

[features]
default = []
console = ["console-subscriber"]
[target.'cfg(windows)'.dependencies]
windows = { version = "0.56", features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
    "Win32_System_Console",
] }

