[package]
name = "client"
version = "1.0.0-rc"
edition = "2021"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
tokio         = { version = "1", features = ["full"] }
fast-socks5   = "1"
rustls        = { version = "0.23", features = ["ring"] }
tokio-rustls  = "0.26"
webpki-roots  = "0.26"
tokio-tungstenite = { version = "0.26" }   # 不带 rustls feature，手动做 TLS
futures-util  = "0.3"
anyhow        = "1"
tracing       = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
base64        = "0.22"
rand          = "0.9"
url           = "2"
clap          = { version = "4", features = ["derive"] }
serde         = { version = "1", features = ["derive"] }
serde_yaml    = "0.9"
bytes         = "1"
libc          = "0.2"
socket2       = { version = "0.5", features = ["all"] }
[target.'cfg(windows)'.dependencies]
windows = { version = "0.56", features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock"
] }

[profile.release]
opt-level    = "z"
strip        = true
lto          = true
codegen-units = 1
panic        = "abort"
