[package]
name = "gui"
version.workspace = true
edition.workspace = true

[dependencies]
eframe = { version = "0.29", default-features = false, features = ["wgpu", "glow", "default_fonts"] }
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
log = "0.4"
