[package]
name = "server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
protocol       = { path = "../protocol" }
tokio          = { version = "1", features = ["full"] }
axum           = { version = "0.8", features = ["ws"] }
futures-util   = "0.3"
anyhow         = "1"
tracing        = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap           = { version = "4", features = ["derive"] }
serde          = { version = "1", features = ["derive"] }
serde_yaml     = "0.9"
bytes          = "1"
dashmap        = "6"
libc           = "0.2"
console-subscriber = { version = "0.5", optional = true }

[features]
default = []
console = ["console-subscriber"]
