[package]
name = "proxy"
version = "1.0.0-rc"
edition = "2021"

[[bin]]
name = "proxy"
path = "src/main.rs"

[dependencies]
tokio        = { version = "1", features = ["full"] }
anyhow       = "1"
tracing      = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap         = { version = "4", features = ["derive"] }
serde        = { version = "1", features = ["derive"] }
serde_yaml   = "0.9"
url          = "2"

[target.'cfg(unix)'.dependencies]
libc         = "0.2"

[profile.release]
opt-level    = "z"
strip        = true
lto          = true
codegen-units = 1
panic        = "abort"
